### ISSUE TITLE
deferRender延迟渲染可以提高Datatables的加载速度, 但是对treeGrid有影响，所以置于false。

### ISSUE THREAD

**Issue by LiuwqGit** [homfen/dataTables.treeGrid.js#11]
deferRender: false
延迟渲染可以提高Datatables的加载速度,延迟渲染，对treeGrid有影响，所以置于false。
点击+，不会扩展子集。

**Comment by simon1tan** [comment]
Dang, wish this was in English so that I would have known deferRender: true breaks this.

**Comment by LiuwqGit** [comment]
deferRender deferred rendering can improve the loading speed Datatables, but for treeGrid influential, so put false
