### ISSUE TITLE
当多层数据时，第一个子集没有子集，第二个子集有子集时，在子集都展开的情况下点击父级收缩会出现死循环

### ISSUE THREAD

**Issue by 1483087928** [homfen/dataTables.treeGrid.js#12]
{
    "data": [
        {
            "name": "Tiger Nixon",
            "position": "System Architect",
            "office": "Edinburgh",
            "extn": "5421",
            "start": "2011\/04\/25",
            "salary": "$320,800",
            "children": [
    				{
                        "name": "Shad Decker",
                        "position": "Regional Director",
                        "office": "Edinburgh",
                        "extn": "6373",
                        "start": "2008\/11\/13",
                        "salary": "$183,000"
                    },
            		{
		                "name": "Lael Greer",
		                "position": "Systems Administrator",
		                "office": "London",
		                "extn": "6733",
		                "start": "2009\/02\/27",
		                "salary": "$103,500",
		                "children": [
                    {
                        "name": "Shad Decker",
                        "position": "Regional Director",
                        "office": "Edinburgh",
                        "extn": "6373",
                        "start": "2008\/11\/13",
                        "salary": "$183,000"							
                    },
                    {
                        "name": "Jonas Alexander",
                        "position": "Developer",
                        "office": "San Francisco",
                        "extn": "8196",
                        "start": "2010\/07\/14",
                        "salary": "$86,500",
                        "children":[
	                            {
		                            "name": "Shad Decker",
		                            "position": "Regional Director",
		                            "office": "Edinburgh",
		                            "extn": "6373",
		                            "start": "2008\/11\/13",
		                            "salary": "$183,000",
									"children":[
	                            			{
					                            "name": "Shad Decker",
					                            "position": "Regional Director",
					                            "office": "Edinburgh",
					                            "extn": "6373",
					                            "start": "2008\/11\/13",
					                            "salary": "$183,000"
		                        			}
		                       
                            		]
                   				 }
		                       
                    	]
                        }
                        
                    ]
                }
            ]
        }
    ]
}

**Comment by lhmyy521125** [comment]
This is the author who wrote an incorrect loop. Modify the code to find 275 lines of the getChildrenCollapseIndexes method

`while'(ary. length > 0); revised to while' (ary. length < 0);`

**Comment by homfen** [comment]
@lhmyy521125 `ary. length < 0` is useless, it's forever false.

**Comment by lhmyy521125** [comment]
> @lhmyy521125 `ary. length < 0` is useless, it's forever false.

It is precisely because each time the subset array length > 0 is fetched, because While has always been True, it will be recycled again to cause a dead loop, DEBUG JavaScript will find!

Another problem is that when the multi-level subset shrinks, the expansion below the second level will not delete the problem; the solution uses recursive rewriting getChildrenCollapse Indexes method;

Your plug-in has been repaired by myself. There are no problems in using it in the current project.

**Comment by homfen** [comment]
@lhmyy521125 as you can see this part of code `getChildrenCollapse` was merged from someone else, and I have fixed it now.
