### ISSUE TITLE
TreeGrid v1.0.0 does not work with DataTables v.1.10.19

### ISSUE THREAD

**Issue by atillabaspinar** [homfen/dataTables.treeGrid.js#19]
rows do not expand as plus/minus buttons are clicked. 
I traced the code on browser debugger and I was able to fix it as below:
// Expand TreeGrid
        dataTable.on('click', 'td.treegrid-control', function (e) {
            if (!$(this).html()) {
                return;
            }
            var tr = $(this).closest('tr[role="row"]');

            // record selected indexes
            var selectedIndexes = [];
            select && (selectedIndexes = dataTable.rows({selected:true}).indexes().toArray());
            var tr = $(this).closest('tr[role="row"]'); //ADD THIS LINE
            var row = dataTable.row(tr); //CHANGE THIS LINE FROM var row = dataTable.row(this); //"this" selects the cell, not the row!!!
            var index = row.index();
            var data = row.data();

**Comment by acorbin3** [comment]
FYI, since it sounds like you have a fix you could fork the repo, make a commit, and request a pull request to this repo. 👍

**Comment by AlexLvovsky** [comment]
@atillabaspinar are you planning to make this commit?

**Comment by homfen** [comment]
I've fixed the problem, you can update to the latest commit.
