### ISSUE TITLE
Sort on children column

### ISSUE THREAD

**Issue by maverick42** [homfen/dataTables.treeGrid.js#2]
Hi,

First of all, TreeGrid is a POWERFUL datatable plugin with a simple approach (children)
There is however a small lack for me. When a column is sorted, the column of the child branch is not sorted.
If that had been possible, it would be great !

Best
Frédérik

**Comment by homfen** [comment]
Thanks for the suggestion, I'll check and update it once I'm free.

Best
Homfen
