### ISSUE TITLE
TypeError: data is undefined

### ISSUE THREAD

**Issue by LucieWallee** [homfen/dataTables.treeGrid.js#20]
Hi,
I am trying to reproduce the example that you given. 
I have this code : 
` 
    
    <script type="text/javascript" src='{{ asset('js/DataTables/media/js/jquery.js') }}'></script>
    
    <script type="text/javascript" src='{{ asset('js/DataTables/media/js/jquery.dataTables.min.js') }}'></script>
    
    <script type="text/javascript" src='{{ asset('js/dataTables.treeGrid/dataTables.treeGrid.js') }}'></script>

    <script>
        var columns = [
            {
                title: '',
                target: 0,
                className: 'treegrid-control',
                data: function (item) {
                    if (item.children) {
                        return '<span>+</span>';
                    }
                    return '';
                }
            },
            {
                title: 'Name',
                target: 1,
                data: function (item) {
                    return item.name;
                }
            },
            {
                title: 'Position',
                target: 2,
                data: function (item) {
                    return item.position;
                }
            },
            {
                title: 'Office',
                target: 3,
                data: function (item) {
                    return item.office;
                }
            },
            {
                title: 'Extn.',
                target: 4,
                data: function (item) {
                    return item.extn;
                }
            },
            {
                title: 'Start date',
                target: 5,
                data: function (item) {
                    return item.start;
                }
            },
            {
                title: 'Salary',
                target: 6,
                data: function (item) {
                    return item.salary;
                }
            }
        ];

        $('#example').DataTable({
            'columns': columns,
            'ajax': "{{ asset('js/arrays.json') }}",
            'treeGrid': {
                'left': 10,
                'expandIcon': '<span>+</span>',
                'collapseIcon': '<span>-</span>'
            }
        });
    </script>
`

And my file arrays.json contains is ine the same format of your example. 

So in my dispplay I have that : 
![image](https://user-images.githubusercontent.com/29482443/42509312-ca659e40-844b-11e8-9faa-4cad1cc4dc6f.png)

My problem is, when I click on "+" or "-" I have this message in my console : 
![image](https://user-images.githubusercontent.com/29482443/42509373-f1230f68-844b-11e8-8a38-7e26a8c97441.png)

" [Afficher/Masquer les détails du message.] TypeError: data is undefined[En savoir plus] dataTables.treeGrid.js:140:1
fnConstruct/<
http://localhost/gestion_MKT/web/js/dataTables.treeGrid/dataTables.treeGrid.js:140:1
dispatch
http://localhost/gestion_MKT/web/js/DataTables/media/js/jquery.js:3:12392
add/r.handle
http://localhost/gestion_MKT/web/js/DataTables/media/js/jquery.js:3:9156
"

I hope you cna help me to understand why it doesn't work. 

Thank you.

**Comment by homfen** [comment]
I have fixed it.
