### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by mail2dve** [homfen/dataTables.treeGrid.js#28]
1. for child rows not called callback function of dataTable  "fnRowCallback"

2. after expand parent row  attribute "id" changed to id="tr-1549374473989"

3. for file version 1.0.1 not fixed  TreeGrid.version = '1.0.0';

**Comment by homfen** [comment]
@mail2dve 
1. have no plan to add "fnRowCallback" at present
2. have changed "id" to "tg-id"
3. have fixed the version number
