### ISSUE TITLE
error mark rows as selected on expand row

### ISSUE THREAD

**Issue by mail2dve** [homfen/dataTables.treeGrid.js#29]
After expand row in dataTable mark as selected more then one row

Source row 117 is :
select && (selectedIndexes = dataTable.rows({selected: true}).indexes().toArray());

Check for variable:
dataTable.rows({selected: true}).indexes().toArray();
Console: (2) [0, 1]

dataTable.rows(".selected").indexes().toArray();
Console: [1]

**Comment by homfen** [comment]
![image](https://user-images.githubusercontent.com/973826/52771390-c15bcc80-3070-11e9-9d8d-24ae1c7a2de6.png)

Maybe you miss the opportunity.
