### ISSUE TITLE
 expand all by default

### ISSUE THREAD

**Issue by DawnOct** [homfen/dataTables.treeGrid.js#6]
Does it possible to make it expand all by default?
Thanks

**Comment by fr0z3nfyr** [comment]
It would be great to have this feature - expand/collapse all nodes at initialization. Any ideas for a workaround until this is made available as a part of this plugin?

**Comment by simon1tan** [comment]
You can do a click() event on all of them. Pretty simple to do.

**Comment by fr0z3nfyr** [comment]
@simon1tan: It would be a JS nuisance if the tree is long and deep.

**Comment by fr0z3nfyr** [comment]
Had expected a solution to this enhancement instead of getting closed without a comment
